In [142]:
import polars as pl
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
from linearmodels.iv import compare
from linearmodels.panel.results import compare
import statsmodels.api as sm
from statsmodels.api import qqplot
from linearmodels.panel import PanelOLS
from scipy import stats as scipy_stats

import pyreadstat as prs
import pygwalker as pyg

import altair as alt
import seaborn as sns
import matplotlib.pyplot as plt

import json

from tqdm.notebook import tqdm
from itables import init_notebook_mode

alt.data_transformers.enable("vegafusion")

DataTransformerRegistry.enable('vegafusion')

# add variables

In [143]:
additional_health_variables = pl.read_excel('../data/disease_variables.xlsx')
additional_health_variables

shape: (10, 3)
┌─────────┬──────────────────┬──────┐
│ var     ┆ label            ┆ fill │
│ ---     ┆ ---              ┆ ---  │
│ str     ┆ str              ┆ str  │
╞═════════╪══════════════════╪══════╡
│ m20_61  ┆ chronic_heart    ┆ no   │
│ m20_62  ┆ chronic_lung     ┆ no   │
│ m20_63  ┆ chronic_liver    ┆ no   │
│ m20_64  ┆ chronic_kidney   ┆ no   │
│ m20_65  ┆ chronic_stomach  ┆ no   │
│ m20_66  ┆ chronic_spinal   ┆ no   │
│ m20_612 ┆ disease_neuro    ┆ no   │
│ m20_613 ┆ disease_eye      ┆ no   │
│ m20_615 ┆ allegies         ┆ no   │
│ m20_8   ┆ disability_class ┆ no   │
└─────────┴──────────────────┴──────┘

In [144]:
cols_disease = additional_health_variables['var'].to_list()
cols_disease

['m20_61',
 'm20_62',
 'm20_63',
 'm20_64',
 'm20_65',
 'm20_66',
 'm20_612',
 'm20_613',
 'm20_615',
 'm20_8']

In [145]:
cols = ['idind', 'year', 'h7_2', 'h7_1', 'origsm', 'region', 'psu', 'status', 'age', 'educ', 'marst', 'h5', 'm20_7', 'j1', 'j60', 'j40', 'j363']

In [146]:
cols + cols_disease

['idind',
 'year',
 'h7_2',
 'h7_1',
 'origsm',
 'region',
 'psu',
 'status',
 'age',
 'educ',
 'marst',
 'h5',
 'm20_7',
 'j1',
 'j60',
 'j40',
 'j363',
 'm20_61',
 'm20_62',
 'm20_63',
 'm20_64',
 'm20_65',
 'm20_66',
 'm20_612',
 'm20_613',
 'm20_615',
 'm20_8']

In [147]:
education_levels = pl.read_excel('../data/all_education_levels.xlsx', sheet_name='selected_levels')
education_levels

shape: (22, 2)
┌─────────────────────────────────┬────────────────┐
│ educ                            ┆ educ_level     │
│ ---                             ┆ ---            │
│ str                             ┆ str            │
╞═════════════════════════════════╪════════════════╡
│ 1-2 years in Institute, Univer… ┆ university     │
│ 7 grades of school              ┆ school_or_less │
│ 6 grades of school              ┆ school_or_less │
│ 3 grades of school              ┆ school_or_less │
│ 7-9 grades of school [unfinish… ┆ common         │
│ …                               ┆ …              │
│ 7-9 grades of school [unfinish… ┆ common         │
│ Graduate school, residency wit… ┆ common         │
│ 10 and more grades of school &… ┆ higher         │
│ Technical, medical, musis etc … ┆ common         │
│ 9 grades of school              ┆ common         │
└─────────────────────────────────┴────────────────┘

In [148]:
marital_status = pl.read_excel('../data/all_marst_levels.xlsx', sheet_name='selected_levels')
marital_status

shape: (6, 2)
┌─────────────────────────────────┬────────────┐
│ marst                           ┆ is_married │
│ ---                             ┆ ---        │
│ str                             ┆ i64        │
╞═════════════════════════════════╪════════════╡
│ In a registered marriage        ┆ 1          │
│ Divorsed and not remarried      ┆ 0          │
│ Living together, not registere… ┆ 1          │
│ Registered, not living togethe… ┆ 1          │
│ Never married                   ┆ 0          │
│ Widower or widow                ┆ 0          │
└─────────────────────────────────┴────────────┘

In [149]:
period_relevance = pl.read_excel('../data/period_relevance.xlsx').with_columns(
    pl.col('year').cast(pl.Float64)
)
period_relevance

shape: (11, 2)
┌────────┬──────────────────┐
│ year   ┆ period_relevance │
│ ---    ┆ ---              │
│ f64    ┆ i64              │
╞════════╪══════════════════╡
│ 2014.0 ┆ -5               │
│ 2015.0 ┆ -4               │
│ 2016.0 ┆ -3               │
│ 2017.0 ┆ -2               │
│ 2018.0 ┆ -1               │
│ …      ┆ …                │
│ 2020.0 ┆ 1                │
│ 2021.0 ┆ 2                │
│ 2022.0 ┆ 3                │
│ 2023.0 ┆ 4                │
│ 2024.0 ┆ 5                │
└────────┴──────────────────┘

In [150]:
is_town = pl.read_excel('../data/is_town.xlsx')
is_town

shape: (4, 2)
┌──────────────────┬─────────┐
│ status           ┆ is_town │
│ ---              ┆ ---     │
│ str              ┆ i64     │
╞══════════════════╪═════════╡
│ town             ┆ 1       │
│ oblastnoy center ┆ 1       │
│ PGT              ┆ 1       │
│ rural            ┆ 0       │
└──────────────────┴─────────┘

In [151]:
panel = pl.read_parquet('../data/RLMS_IND_2015_2024_eng_prepared.parquet', columns=cols + cols_disease)
for var, label, fill in zip(additional_health_variables['var'], additional_health_variables['label'], additional_health_variables['fill']):
    panel = panel.with_columns(
        pl.col(var).fill_null(fill).alias(label)
    )
panel

shape: (179_176, 37)
┌─────────┬────────┬──────────┬──────┬───┬───────────────┬─────────────┬──────────┬────────────────┐
│ idind   ┆ year   ┆ h7_2     ┆ h7_1 ┆ … ┆ disease_neuro ┆ disease_eye ┆ allegies ┆ disability_cla │
│ ---     ┆ ---    ┆ ---      ┆ ---  ┆   ┆ ---           ┆ ---         ┆ ---      ┆ ss             │
│ f64     ┆ f64    ┆ str      ┆ f64  ┆   ┆ str           ┆ str         ┆ str      ┆ ---            │
│         ┆        ┆          ┆      ┆   ┆               ┆             ┆          ┆ str            │
╞═════════╪════════╪══════════╪══════╪═══╪═══════════════╪═════════════╪══════════╪════════════════╡
│ 34896.0 ┆ 2014.0 ┆ January  ┆ 5.0  ┆ … ┆ No            ┆ No          ┆ No       ┆ no             │
│ 34897.0 ┆ 2014.0 ┆ January  ┆ 5.0  ┆ … ┆ No            ┆ No          ┆ No       ┆ no             │
│ 34907.0 ┆ 2014.0 ┆ January  ┆ 18.0 ┆ … ┆ No            ┆ No          ┆ No       ┆ Third group    │
│ 34908.0 ┆ 2014.0 ┆ January  ┆ 18.0 ┆ … ┆ No            ┆ No          ┆ No       ┆ no             │
│ 34919.0 ┆ 2014.0 ┆ January  ┆ 19.0 ┆ … ┆ No            ┆ No          ┆ No       ┆ no             │
│ …       ┆ …      ┆ …        ┆ …    ┆ … ┆ …             ┆ …           ┆ …        ┆ …              │
│ 59407.0 ┆ 2024.0 ┆ November ┆ 27.0 ┆ … ┆ No            ┆ No          ┆ No       ┆ no             │
│ 59408.0 ┆ 2024.0 ┆ October  ┆ 9.0  ┆ … ┆ No            ┆ No          ┆ Yes      ┆ no             │
│ 59409.0 ┆ 2024.0 ┆ October  ┆ 11.0 ┆ … ┆ No            ┆ No          ┆ No       ┆ no             │
│ 59412.0 ┆ 2024.0 ┆ October  ┆ 11.0 ┆ … ┆ Yes           ┆ Yes         ┆ Yes      ┆ Second group   │
│ 59413.0 ┆ 2024.0 ┆ October  ┆ 11.0 ┆ … ┆ No            ┆ No          ┆ No       ┆ no             │
└─────────┴────────┴──────────┴──────┴───┴───────────────┴─────────────┴──────────┴────────────────┘

In [152]:
panel = panel.with_columns(
    date = pl.concat_str([pl.col('year').cast(pl.Int32), pl.col('h7_2'), pl.col('h7_1').cast(pl.Int32)], separator=' ').str.strptime(pl.Date, format='%Y %B %d')
)
panel

shape: (179_176, 38)
┌─────────┬────────┬──────────┬──────┬───┬─────────────┬──────────┬──────────────────┬────────────┐
│ idind   ┆ year   ┆ h7_2     ┆ h7_1 ┆ … ┆ disease_eye ┆ allegies ┆ disability_class ┆ date       │
│ ---     ┆ ---    ┆ ---      ┆ ---  ┆   ┆ ---         ┆ ---      ┆ ---              ┆ ---        │
│ f64     ┆ f64    ┆ str      ┆ f64  ┆   ┆ str         ┆ str      ┆ str              ┆ date       │
╞═════════╪════════╪══════════╪══════╪═══╪═════════════╪══════════╪══════════════════╪════════════╡
│ 34896.0 ┆ 2014.0 ┆ January  ┆ 5.0  ┆ … ┆ No          ┆ No       ┆ no               ┆ 2014-01-05 │
│ 34897.0 ┆ 2014.0 ┆ January  ┆ 5.0  ┆ … ┆ No          ┆ No       ┆ no               ┆ 2014-01-05 │
│ 34907.0 ┆ 2014.0 ┆ January  ┆ 18.0 ┆ … ┆ No          ┆ No       ┆ Third group      ┆ 2014-01-18 │
│ 34908.0 ┆ 2014.0 ┆ January  ┆ 18.0 ┆ … ┆ No          ┆ No       ┆ no               ┆ 2014-01-18 │
│ 34919.0 ┆ 2014.0 ┆ January  ┆ 19.0 ┆ … ┆ No          ┆ No       ┆ no               ┆ 2014-01-19 │
│ …       ┆ …      ┆ …        ┆ …    ┆ … ┆ …           ┆ …        ┆ …                ┆ …          │
│ 59407.0 ┆ 2024.0 ┆ November ┆ 27.0 ┆ … ┆ No          ┆ No       ┆ no               ┆ 2024-11-27 │
│ 59408.0 ┆ 2024.0 ┆ October  ┆ 9.0  ┆ … ┆ No          ┆ Yes      ┆ no               ┆ 2024-10-09 │
│ 59409.0 ┆ 2024.0 ┆ October  ┆ 11.0 ┆ … ┆ No          ┆ No       ┆ no               ┆ 2024-10-11 │
│ 59412.0 ┆ 2024.0 ┆ October  ┆ 11.0 ┆ … ┆ Yes         ┆ Yes      ┆ Second group     ┆ 2024-10-11 │
│ 59413.0 ┆ 2024.0 ┆ October  ┆ 11.0 ┆ … ┆ No          ┆ No       ┆ no               ┆ 2024-10-11 │
└─────────┴────────┴──────────┴──────┴───┴─────────────┴──────────┴──────────────────┴────────────┘

In [153]:
panel = panel.with_columns(
    is_employed = pl.when(pl.col('j1').is_in(['You are currently working', 'You are on paid leave: maternity leave or taking care of a child under 3 years o', 'You are on another kind of paid leave'])).then(1).otherwise(0)
)
panel

shape: (179_176, 39)
┌─────────┬────────┬──────────┬──────┬───┬──────────┬──────────────────┬────────────┬─────────────┐
│ idind   ┆ year   ┆ h7_2     ┆ h7_1 ┆ … ┆ allegies ┆ disability_class ┆ date       ┆ is_employed │
│ ---     ┆ ---    ┆ ---      ┆ ---  ┆   ┆ ---      ┆ ---              ┆ ---        ┆ ---         │
│ f64     ┆ f64    ┆ str      ┆ f64  ┆   ┆ str      ┆ str              ┆ date       ┆ i32         │
╞═════════╪════════╪══════════╪══════╪═══╪══════════╪══════════════════╪════════════╪═════════════╡
│ 34896.0 ┆ 2014.0 ┆ January  ┆ 5.0  ┆ … ┆ No       ┆ no               ┆ 2014-01-05 ┆ 1           │
│ 34897.0 ┆ 2014.0 ┆ January  ┆ 5.0  ┆ … ┆ No       ┆ no               ┆ 2014-01-05 ┆ 0           │
│ 34907.0 ┆ 2014.0 ┆ January  ┆ 18.0 ┆ … ┆ No       ┆ Third group      ┆ 2014-01-18 ┆ 0           │
│ 34908.0 ┆ 2014.0 ┆ January  ┆ 18.0 ┆ … ┆ No       ┆ no               ┆ 2014-01-18 ┆ 1           │
│ 34919.0 ┆ 2014.0 ┆ January  ┆ 19.0 ┆ … ┆ No       ┆ no               ┆ 2014-01-19 ┆ 1           │
│ …       ┆ …      ┆ …        ┆ …    ┆ … ┆ …        ┆ …                ┆ …          ┆ …           │
│ 59407.0 ┆ 2024.0 ┆ November ┆ 27.0 ┆ … ┆ No       ┆ no               ┆ 2024-11-27 ┆ 0           │
│ 59408.0 ┆ 2024.0 ┆ October  ┆ 9.0  ┆ … ┆ Yes      ┆ no               ┆ 2024-10-09 ┆ 0           │
│ 59409.0 ┆ 2024.0 ┆ October  ┆ 11.0 ┆ … ┆ No       ┆ no               ┆ 2024-10-11 ┆ 0           │
│ 59412.0 ┆ 2024.0 ┆ October  ┆ 11.0 ┆ … ┆ Yes      ┆ Second group     ┆ 2024-10-11 ┆ 0           │
│ 59413.0 ┆ 2024.0 ┆ October  ┆ 11.0 ┆ … ┆ No       ┆ no               ┆ 2024-10-11 ┆ 0           │
└─────────┴────────┴──────────┴──────┴───┴──────────┴──────────────────┴────────────┴─────────────┘

In [154]:
panel = panel.with_columns(
    has_disablity = pl.when(pl.col('m20_7').is_in(['No', 'NO ANSWER'])).then(0).otherwise(1)
)
panel

shape: (179_176, 40)
┌─────────┬────────┬──────────┬──────┬───┬───────────────┬────────────┬─────────────┬──────────────┐
│ idind   ┆ year   ┆ h7_2     ┆ h7_1 ┆ … ┆ disability_cl ┆ date       ┆ is_employed ┆ has_disablit │
│ ---     ┆ ---    ┆ ---      ┆ ---  ┆   ┆ ass           ┆ ---        ┆ ---         ┆ y            │
│ f64     ┆ f64    ┆ str      ┆ f64  ┆   ┆ ---           ┆ date       ┆ i32         ┆ ---          │
│         ┆        ┆          ┆      ┆   ┆ str           ┆            ┆             ┆ i32          │
╞═════════╪════════╪══════════╪══════╪═══╪═══════════════╪════════════╪═════════════╪══════════════╡
│ 34896.0 ┆ 2014.0 ┆ January  ┆ 5.0  ┆ … ┆ no            ┆ 2014-01-05 ┆ 1           ┆ 0            │
│ 34897.0 ┆ 2014.0 ┆ January  ┆ 5.0  ┆ … ┆ no            ┆ 2014-01-05 ┆ 0           ┆ 0            │
│ 34907.0 ┆ 2014.0 ┆ January  ┆ 18.0 ┆ … ┆ Third group   ┆ 2014-01-18 ┆ 0           ┆ 1            │
│ 34908.0 ┆ 2014.0 ┆ January  ┆ 18.0 ┆ … ┆ no            ┆ 2014-01-18 ┆ 1           ┆ 0            │
│ 34919.0 ┆ 2014.0 ┆ January  ┆ 19.0 ┆ … ┆ no            ┆ 2014-01-19 ┆ 1           ┆ 0            │
│ …       ┆ …      ┆ …        ┆ …    ┆ … ┆ …             ┆ …          ┆ …           ┆ …            │
│ 59407.0 ┆ 2024.0 ┆ November ┆ 27.0 ┆ … ┆ no            ┆ 2024-11-27 ┆ 0           ┆ 0            │
│ 59408.0 ┆ 2024.0 ┆ October  ┆ 9.0  ┆ … ┆ no            ┆ 2024-10-09 ┆ 0           ┆ 0            │
│ 59409.0 ┆ 2024.0 ┆ October  ┆ 11.0 ┆ … ┆ no            ┆ 2024-10-11 ┆ 0           ┆ 0            │
│ 59412.0 ┆ 2024.0 ┆ October  ┆ 11.0 ┆ … ┆ Second group  ┆ 2024-10-11 ┆ 0           ┆ 1            │
│ 59413.0 ┆ 2024.0 ┆ October  ┆ 11.0 ┆ … ┆ no            ┆ 2024-10-11 ┆ 0           ┆ 0            │
└─────────┴────────┴──────────┴──────┴───┴───────────────┴────────────┴─────────────┴──────────────┘

In [155]:
panel = panel.with_columns(
    is_employed_has_disablity = pl.col('is_employed') * pl.col('has_disablity')
)
panel

shape: (179_176, 41)
┌─────────┬────────┬──────────┬──────┬───┬────────────┬─────────────┬───────────────┬──────────────┐
│ idind   ┆ year   ┆ h7_2     ┆ h7_1 ┆ … ┆ date       ┆ is_employed ┆ has_disablity ┆ is_employed_ │
│ ---     ┆ ---    ┆ ---      ┆ ---  ┆   ┆ ---        ┆ ---         ┆ ---           ┆ has_disablit │
│ f64     ┆ f64    ┆ str      ┆ f64  ┆   ┆ date       ┆ i32         ┆ i32           ┆ y            │
│         ┆        ┆          ┆      ┆   ┆            ┆             ┆               ┆ ---          │
│         ┆        ┆          ┆      ┆   ┆            ┆             ┆               ┆ i32          │
╞═════════╪════════╪══════════╪══════╪═══╪════════════╪═════════════╪═══════════════╪══════════════╡
│ 34896.0 ┆ 2014.0 ┆ January  ┆ 5.0  ┆ … ┆ 2014-01-05 ┆ 1           ┆ 0             ┆ 0            │
│ 34897.0 ┆ 2014.0 ┆ January  ┆ 5.0  ┆ … ┆ 2014-01-05 ┆ 0           ┆ 0             ┆ 0            │
│ 34907.0 ┆ 2014.0 ┆ January  ┆ 18.0 ┆ … ┆ 2014-01-18 ┆ 0           ┆ 1             ┆ 0            │
│ 34908.0 ┆ 2014.0 ┆ January  ┆ 18.0 ┆ … ┆ 2014-01-18 ┆ 1           ┆ 0             ┆ 0            │
│ 34919.0 ┆ 2014.0 ┆ January  ┆ 19.0 ┆ … ┆ 2014-01-19 ┆ 1           ┆ 0             ┆ 0            │
│ …       ┆ …      ┆ …        ┆ …    ┆ … ┆ …          ┆ …           ┆ …             ┆ …            │
│ 59407.0 ┆ 2024.0 ┆ November ┆ 27.0 ┆ … ┆ 2024-11-27 ┆ 0           ┆ 0             ┆ 0            │
│ 59408.0 ┆ 2024.0 ┆ October  ┆ 9.0  ┆ … ┆ 2024-10-09 ┆ 0           ┆ 0             ┆ 0            │
│ 59409.0 ┆ 2024.0 ┆ October  ┆ 11.0 ┆ … ┆ 2024-10-11 ┆ 0           ┆ 0             ┆ 0            │
│ 59412.0 ┆ 2024.0 ┆ October  ┆ 11.0 ┆ … ┆ 2024-10-11 ┆ 0           ┆ 1             ┆ 0            │
│ 59413.0 ┆ 2024.0 ┆ October  ┆ 11.0 ┆ … ┆ 2024-10-11 ┆ 0           ┆ 0             ┆ 0            │
└─────────┴────────┴──────────┴──────┴───┴────────────┴─────────────┴───────────────┴──────────────┘

In [156]:
panel = panel.with_columns(
    is_employed_no_disablity = pl.col('is_employed') * pl.col('has_disablity').replace({0:1, 1:0})
)
panel

shape: (179_176, 42)
┌─────────┬────────┬──────────┬──────┬───┬─────────────┬──────────────┬──────────────┬─────────────┐
│ idind   ┆ year   ┆ h7_2     ┆ h7_1 ┆ … ┆ is_employed ┆ has_disablit ┆ is_employed_ ┆ is_employed │
│ ---     ┆ ---    ┆ ---      ┆ ---  ┆   ┆ ---         ┆ y            ┆ has_disablit ┆ _no_disabli │
│ f64     ┆ f64    ┆ str      ┆ f64  ┆   ┆ i32         ┆ ---          ┆ y            ┆ ty          │
│         ┆        ┆          ┆      ┆   ┆             ┆ i32          ┆ ---          ┆ ---         │
│         ┆        ┆          ┆      ┆   ┆             ┆              ┆ i32          ┆ i32         │
╞═════════╪════════╪══════════╪══════╪═══╪═════════════╪══════════════╪══════════════╪═════════════╡
│ 34896.0 ┆ 2014.0 ┆ January  ┆ 5.0  ┆ … ┆ 1           ┆ 0            ┆ 0            ┆ 1           │
│ 34897.0 ┆ 2014.0 ┆ January  ┆ 5.0  ┆ … ┆ 0           ┆ 0            ┆ 0            ┆ 0           │
│ 34907.0 ┆ 2014.0 ┆ January  ┆ 18.0 ┆ … ┆ 0           ┆ 1            ┆ 0            ┆ 0           │
│ 34908.0 ┆ 2014.0 ┆ January  ┆ 18.0 ┆ … ┆ 1           ┆ 0            ┆ 0            ┆ 1           │
│ 34919.0 ┆ 2014.0 ┆ January  ┆ 19.0 ┆ … ┆ 1           ┆ 0            ┆ 0            ┆ 1           │
│ …       ┆ …      ┆ …        ┆ …    ┆ … ┆ …           ┆ …            ┆ …            ┆ …           │
│ 59407.0 ┆ 2024.0 ┆ November ┆ 27.0 ┆ … ┆ 0           ┆ 0            ┆ 0            ┆ 0           │
│ 59408.0 ┆ 2024.0 ┆ October  ┆ 9.0  ┆ … ┆ 0           ┆ 0            ┆ 0            ┆ 0           │
│ 59409.0 ┆ 2024.0 ┆ October  ┆ 11.0 ┆ … ┆ 0           ┆ 0            ┆ 0            ┆ 0           │
│ 59412.0 ┆ 2024.0 ┆ October  ┆ 11.0 ┆ … ┆ 0           ┆ 1            ┆ 0            ┆ 0           │
│ 59413.0 ┆ 2024.0 ┆ October  ┆ 11.0 ┆ … ┆ 0           ┆ 0            ┆ 0            ┆ 0           │
└─────────┴────────┴──────────┴──────┴───┴─────────────┴──────────────┴──────────────┴─────────────┘

In [157]:
panel = panel.with_columns(
    net_job = pl.col('j60').fill_null(0) - pl.col('j363').fill_null(0)
)
panel = panel.with_columns(
    pl.when(pl.col('net_job') < 0).then(0).otherwise('net_job').alias('net_job')
)
# panel = panel.with_columns(
#     pl.when(pl.col('is_employed') == 0).then(0).otherwise('net_job').alias('net_job')
# ) 
panel

shape: (179_176, 43)
┌─────────┬────────┬──────────┬──────┬───┬───────────────┬───────────────┬───────────────┬─────────┐
│ idind   ┆ year   ┆ h7_2     ┆ h7_1 ┆ … ┆ has_disablity ┆ is_employed_h ┆ is_employed_n ┆ net_job │
│ ---     ┆ ---    ┆ ---      ┆ ---  ┆   ┆ ---           ┆ as_disablity  ┆ o_disablity   ┆ ---     │
│ f64     ┆ f64    ┆ str      ┆ f64  ┆   ┆ i32           ┆ ---           ┆ ---           ┆ f64     │
│         ┆        ┆          ┆      ┆   ┆               ┆ i32           ┆ i32           ┆         │
╞═════════╪════════╪══════════╪══════╪═══╪═══════════════╪═══════════════╪═══════════════╪═════════╡
│ 34896.0 ┆ 2014.0 ┆ January  ┆ 5.0  ┆ … ┆ 0             ┆ 0             ┆ 1             ┆ 30000.0 │
│ 34897.0 ┆ 2014.0 ┆ January  ┆ 5.0  ┆ … ┆ 0             ┆ 0             ┆ 0             ┆ 800.0   │
│ 34907.0 ┆ 2014.0 ┆ January  ┆ 18.0 ┆ … ┆ 1             ┆ 0             ┆ 0             ┆ 0.0     │
│ 34908.0 ┆ 2014.0 ┆ January  ┆ 18.0 ┆ … ┆ 0             ┆ 0             ┆ 1             ┆ 7000.0  │
│ 34919.0 ┆ 2014.0 ┆ January  ┆ 19.0 ┆ … ┆ 0             ┆ 0             ┆ 1             ┆ 4500.0  │
│ …       ┆ …      ┆ …        ┆ …    ┆ … ┆ …             ┆ …             ┆ …             ┆ …       │
│ 59407.0 ┆ 2024.0 ┆ November ┆ 27.0 ┆ … ┆ 0             ┆ 0             ┆ 0             ┆ 0.0     │
│ 59408.0 ┆ 2024.0 ┆ October  ┆ 9.0  ┆ … ┆ 0             ┆ 0             ┆ 0             ┆ 0.0     │
│ 59409.0 ┆ 2024.0 ┆ October  ┆ 11.0 ┆ … ┆ 0             ┆ 0             ┆ 0             ┆ 0.0     │
│ 59412.0 ┆ 2024.0 ┆ October  ┆ 11.0 ┆ … ┆ 1             ┆ 0             ┆ 0             ┆ 3577.0  │
│ 59413.0 ┆ 2024.0 ┆ October  ┆ 11.0 ┆ … ┆ 0             ┆ 0             ┆ 0             ┆ 4100.0  │
└─────────┴────────┴──────────┴──────┴───┴───────────────┴───────────────┴───────────────┴─────────┘

In [158]:
panel  = panel.filter(pl.col('net_job') < 1_000_000)
panel

shape: (179_148, 43)
┌─────────┬────────┬──────────┬──────┬───┬───────────────┬───────────────┬───────────────┬─────────┐
│ idind   ┆ year   ┆ h7_2     ┆ h7_1 ┆ … ┆ has_disablity ┆ is_employed_h ┆ is_employed_n ┆ net_job │
│ ---     ┆ ---    ┆ ---      ┆ ---  ┆   ┆ ---           ┆ as_disablity  ┆ o_disablity   ┆ ---     │
│ f64     ┆ f64    ┆ str      ┆ f64  ┆   ┆ i32           ┆ ---           ┆ ---           ┆ f64     │
│         ┆        ┆          ┆      ┆   ┆               ┆ i32           ┆ i32           ┆         │
╞═════════╪════════╪══════════╪══════╪═══╪═══════════════╪═══════════════╪═══════════════╪═════════╡
│ 34896.0 ┆ 2014.0 ┆ January  ┆ 5.0  ┆ … ┆ 0             ┆ 0             ┆ 1             ┆ 30000.0 │
│ 34897.0 ┆ 2014.0 ┆ January  ┆ 5.0  ┆ … ┆ 0             ┆ 0             ┆ 0             ┆ 800.0   │
│ 34907.0 ┆ 2014.0 ┆ January  ┆ 18.0 ┆ … ┆ 1             ┆ 0             ┆ 0             ┆ 0.0     │
│ 34908.0 ┆ 2014.0 ┆ January  ┆ 18.0 ┆ … ┆ 0             ┆ 0             ┆ 1             ┆ 7000.0  │
│ 34919.0 ┆ 2014.0 ┆ January  ┆ 19.0 ┆ … ┆ 0             ┆ 0             ┆ 1             ┆ 4500.0  │
│ …       ┆ …      ┆ …        ┆ …    ┆ … ┆ …             ┆ …             ┆ …             ┆ …       │
│ 59407.0 ┆ 2024.0 ┆ November ┆ 27.0 ┆ … ┆ 0             ┆ 0             ┆ 0             ┆ 0.0     │
│ 59408.0 ┆ 2024.0 ┆ October  ┆ 9.0  ┆ … ┆ 0             ┆ 0             ┆ 0             ┆ 0.0     │
│ 59409.0 ┆ 2024.0 ┆ October  ┆ 11.0 ┆ … ┆ 0             ┆ 0             ┆ 0             ┆ 0.0     │
│ 59412.0 ┆ 2024.0 ┆ October  ┆ 11.0 ┆ … ┆ 1             ┆ 0             ┆ 0             ┆ 3577.0  │
│ 59413.0 ┆ 2024.0 ┆ October  ┆ 11.0 ┆ … ┆ 0             ┆ 0             ┆ 0             ┆ 4100.0  │
└─────────┴────────┴──────────┴──────┴───┴───────────────┴───────────────┴───────────────┴─────────┘

In [159]:
(
    panel
        .filter((pl.col('is_employed_no_disablity') == 1)|(pl.col('is_employed_has_disablity') == 1))
        .with_columns(pl.col('year').cast(pl.Int32).cast(pl.String).str.to_date("%Y"))
        .group_by(['year', 'has_disablity']).agg(pl.col('net_job').mean())
)#.plot.line(x='year', y='net_job', color='has_disablity')

shape: (22, 3)
┌────────────┬───────────────┬──────────────┐
│ year       ┆ has_disablity ┆ net_job      │
│ ---        ┆ ---           ┆ ---          │
│ date       ┆ i32           ┆ f64          │
╞════════════╪═══════════════╪══════════════╡
│ 2017-01-01 ┆ 0             ┆ 27265.28691  │
│ 2023-01-01 ┆ 0             ┆ 44485.484193 │
│ 2020-01-01 ┆ 1             ┆ 25589.862595 │
│ 2016-01-01 ┆ 0             ┆ 25519.360187 │
│ 2022-01-01 ┆ 1             ┆ 32208.307086 │
│ …          ┆ …             ┆ …            │
│ 2017-01-01 ┆ 1             ┆ 21718.952857 │
│ 2023-01-01 ┆ 1             ┆ 35548.351724 │
│ 2016-01-01 ┆ 1             ┆ 19265.172575 │
│ 2018-01-01 ┆ 0             ┆ 28628.620894 │
│ 2020-01-01 ┆ 0             ┆ 32038.929193 │
└────────────┴───────────────┴──────────────┘

In [160]:
panel = panel.with_columns(
    working_pop = pl.when((pl.col('is_employed_no_disablity') == 1)|(pl.col('is_employed_has_disablity') == 1)).then(1).otherwise(0)
)
panel

shape: (179_148, 44)
┌─────────┬────────┬──────────┬──────┬───┬────────────────┬────────────────┬─────────┬─────────────┐
│ idind   ┆ year   ┆ h7_2     ┆ h7_1 ┆ … ┆ is_employed_ha ┆ is_employed_no ┆ net_job ┆ working_pop │
│ ---     ┆ ---    ┆ ---      ┆ ---  ┆   ┆ s_disablity    ┆ _disablity     ┆ ---     ┆ ---         │
│ f64     ┆ f64    ┆ str      ┆ f64  ┆   ┆ ---            ┆ ---            ┆ f64     ┆ i32         │
│         ┆        ┆          ┆      ┆   ┆ i32            ┆ i32            ┆         ┆             │
╞═════════╪════════╪══════════╪══════╪═══╪════════════════╪════════════════╪═════════╪═════════════╡
│ 34896.0 ┆ 2014.0 ┆ January  ┆ 5.0  ┆ … ┆ 0              ┆ 1              ┆ 30000.0 ┆ 1           │
│ 34897.0 ┆ 2014.0 ┆ January  ┆ 5.0  ┆ … ┆ 0              ┆ 0              ┆ 800.0   ┆ 0           │
│ 34907.0 ┆ 2014.0 ┆ January  ┆ 18.0 ┆ … ┆ 0              ┆ 0              ┆ 0.0     ┆ 0           │
│ 34908.0 ┆ 2014.0 ┆ January  ┆ 18.0 ┆ … ┆ 0              ┆ 1              ┆ 7000.0  ┆ 1           │
│ 34919.0 ┆ 2014.0 ┆ January  ┆ 19.0 ┆ … ┆ 0              ┆ 1              ┆ 4500.0  ┆ 1           │
│ …       ┆ …      ┆ …        ┆ …    ┆ … ┆ …              ┆ …              ┆ …       ┆ …           │
│ 59407.0 ┆ 2024.0 ┆ November ┆ 27.0 ┆ … ┆ 0              ┆ 0              ┆ 0.0     ┆ 0           │
│ 59408.0 ┆ 2024.0 ┆ October  ┆ 9.0  ┆ … ┆ 0              ┆ 0              ┆ 0.0     ┆ 0           │
│ 59409.0 ┆ 2024.0 ┆ October  ┆ 11.0 ┆ … ┆ 0              ┆ 0              ┆ 0.0     ┆ 0           │
│ 59412.0 ┆ 2024.0 ┆ October  ┆ 11.0 ┆ … ┆ 0              ┆ 0              ┆ 3577.0  ┆ 0           │
│ 59413.0 ┆ 2024.0 ┆ October  ┆ 11.0 ┆ … ┆ 0              ┆ 0              ┆ 4100.0  ┆ 0           │
└─────────┴────────┴──────────┴──────┴───┴────────────────┴────────────────┴─────────┴─────────────┘

In [161]:
panel_working_pop_2019 = panel.filter(
    #pl.col('date').is_between(pl.date(2019, 1, 1), pl.date(2019, 12, 31))
    pl.col('year') == 2019
)
panel_working_pop_2019

shape: (18_056, 44)
┌─────────┬────────┬──────────┬──────┬───┬────────────────┬────────────────┬─────────┬─────────────┐
│ idind   ┆ year   ┆ h7_2     ┆ h7_1 ┆ … ┆ is_employed_ha ┆ is_employed_no ┆ net_job ┆ working_pop │
│ ---     ┆ ---    ┆ ---      ┆ ---  ┆   ┆ s_disablity    ┆ _disablity     ┆ ---     ┆ ---         │
│ f64     ┆ f64    ┆ str      ┆ f64  ┆   ┆ ---            ┆ ---            ┆ f64     ┆ i32         │
│         ┆        ┆          ┆      ┆   ┆ i32            ┆ i32            ┆         ┆             │
╞═════════╪════════╪══════════╪══════╪═══╪════════════════╪════════════════╪═════════╪═════════════╡
│ 1.0     ┆ 2019.0 ┆ October  ┆ 11.0 ┆ … ┆ 0              ┆ 1              ┆ 37000.0 ┆ 1           │
│ 7.0     ┆ 2019.0 ┆ October  ┆ 9.0  ┆ … ┆ 0              ┆ 0              ┆ 950.0   ┆ 0           │
│ 9.0     ┆ 2019.0 ┆ November ┆ 13.0 ┆ … ┆ 0              ┆ 0              ┆ 0.0     ┆ 0           │
│ 11292.0 ┆ 2019.0 ┆ October  ┆ 15.0 ┆ … ┆ 0              ┆ 0              ┆ 1700.0  ┆ 0           │
│ 3.0     ┆ 2019.0 ┆ October  ┆ 9.0  ┆ … ┆ 1              ┆ 0              ┆ 20600.0 ┆ 1           │
│ …       ┆ …      ┆ …        ┆ …    ┆ … ┆ …              ┆ …              ┆ …       ┆ …           │
│ 59409.0 ┆ 2019.0 ┆ January  ┆ 23.0 ┆ … ┆ 0              ┆ 0              ┆ 0.0     ┆ 0           │
│ 59410.0 ┆ 2019.0 ┆ January  ┆ 28.0 ┆ … ┆ 0              ┆ 1              ┆ 29000.0 ┆ 1           │
│ 59411.0 ┆ 2019.0 ┆ January  ┆ 28.0 ┆ … ┆ 0              ┆ 0              ┆ 1000.0  ┆ 0           │
│ 59412.0 ┆ 2019.0 ┆ January  ┆ 28.0 ┆ … ┆ 0              ┆ 0              ┆ 4600.0  ┆ 0           │
│ 59413.0 ┆ 2019.0 ┆ January  ┆ 28.0 ┆ … ┆ 0              ┆ 0              ┆ 3700.0  ┆ 0           │
└─────────┴────────┴──────────┴──────┴───┴────────────────┴────────────────┴─────────┴─────────────┘

In [162]:
panel_working_pop_2020 = panel.filter(
    #pl.col('date').is_between(pl.date(2020, 1, 1), pl.date(2020, 12, 31))
    pl.col('year') == 2020
)
panel_working_pop_2020

shape: (17_700, 44)
┌─────────┬────────┬───────────┬──────┬───┬────────────────┬───────────────┬─────────┬─────────────┐
│ idind   ┆ year   ┆ h7_2      ┆ h7_1 ┆ … ┆ is_employed_ha ┆ is_employed_n ┆ net_job ┆ working_pop │
│ ---     ┆ ---    ┆ ---       ┆ ---  ┆   ┆ s_disablity    ┆ o_disablity   ┆ ---     ┆ ---         │
│ f64     ┆ f64    ┆ str       ┆ f64  ┆   ┆ ---            ┆ ---           ┆ f64     ┆ i32         │
│         ┆        ┆           ┆      ┆   ┆ i32            ┆ i32           ┆         ┆             │
╞═════════╪════════╪═══════════╪══════╪═══╪════════════════╪═══════════════╪═════════╪═════════════╡
│ 1.0     ┆ 2020.0 ┆ October   ┆ 13.0 ┆ … ┆ 0              ┆ 1             ┆ 37000.0 ┆ 1           │
│ 7.0     ┆ 2020.0 ┆ October   ┆ 8.0  ┆ … ┆ 0              ┆ 0             ┆ 0.0     ┆ 0           │
│ 9.0     ┆ 2020.0 ┆ October   ┆ 28.0 ┆ … ┆ 0              ┆ 0             ┆ 0.0     ┆ 0           │
│ 11292.0 ┆ 2020.0 ┆ November  ┆ 11.0 ┆ … ┆ 0              ┆ 0             ┆ 15800.0 ┆ 0           │
│ 3.0     ┆ 2020.0 ┆ October   ┆ 9.0  ┆ … ┆ 0              ┆ 0             ┆ 700.0   ┆ 0           │
│ …       ┆ …      ┆ …         ┆ …    ┆ … ┆ …              ┆ …             ┆ …       ┆ …           │
│ 59408.0 ┆ 2020.0 ┆ September ┆ 12.0 ┆ … ┆ 0              ┆ 0             ┆ 1000.0  ┆ 0           │
│ 59409.0 ┆ 2020.0 ┆ September ┆ 12.0 ┆ … ┆ 0              ┆ 0             ┆ 0.0     ┆ 0           │
│ 59411.0 ┆ 2020.0 ┆ November  ┆ 29.0 ┆ … ┆ 0              ┆ 0             ┆ 1000.0  ┆ 0           │
│ 59412.0 ┆ 2020.0 ┆ September ┆ 22.0 ┆ … ┆ 0              ┆ 0             ┆ 9100.0  ┆ 0           │
│ 59413.0 ┆ 2020.0 ┆ September ┆ 16.0 ┆ … ┆ 0              ┆ 0             ┆ 3000.0  ┆ 0           │
└─────────┴────────┴───────────┴──────┴───┴────────────────┴───────────────┴─────────┴─────────────┘

In [163]:
common_people = panel_working_pop_2019[['idind']]#.join(panel_working_pop_2020[['idind']], how='inner', on='idind').sort('idind').unique()
common_people

shape: (18_056, 1)
┌─────────┐
│ idind   │
│ ---     │
│ f64     │
╞═════════╡
│ 1.0     │
│ 7.0     │
│ 9.0     │
│ 11292.0 │
│ 3.0     │
│ …       │
│ 59409.0 │
│ 59410.0 │
│ 59411.0 │
│ 59412.0 │
│ 59413.0 │
└─────────┘

In [164]:
people_working_at_least_at_2020_2019 = panel.filter(
    ((pl.col('working_pop') == 1)&(pl.col('year') == 2019)) | ((pl.col('working_pop') == 1)&(pl.col('year') == 2020))
).sort('idind')['idind'].unique().to_frame()
people_working_at_least_at_2020_2019

shape: (8_982, 1)
┌─────────┐
│ idind   │
│ ---     │
│ f64     │
╞═════════╡
│ 1.0     │
│ 3.0     │
│ 6.0     │
│ 29.0    │
│ 30.0    │
│ …       │
│ 60467.0 │
│ 60469.0 │
│ 60470.0 │
│ 60473.0 │
│ 60474.0 │
└─────────┘

In [165]:
common_people = common_people[['idind']].join(people_working_at_least_at_2020_2019[['idind']], how='inner', on='idind').sort('idind').unique()
common_people

shape: (8_269, 1)
┌─────────┐
│ idind   │
│ ---     │
│ f64     │
╞═════════╡
│ 1.0     │
│ 3.0     │
│ 6.0     │
│ 29.0    │
│ 30.0    │
│ …       │
│ 59395.0 │
│ 59397.0 │
│ 59398.0 │
│ 59400.0 │
│ 59410.0 │
└─────────┘

In [166]:
panel_common_2019_2020 = panel.filter(
    pl.col('idind').is_in(common_people['idind'].implode())
).sort('idind')
panel_common_2019_2020

shape: (68_694, 44)
┌─────────┬────────┬───────────┬──────┬───┬────────────────┬───────────────┬─────────┬─────────────┐
│ idind   ┆ year   ┆ h7_2      ┆ h7_1 ┆ … ┆ is_employed_ha ┆ is_employed_n ┆ net_job ┆ working_pop │
│ ---     ┆ ---    ┆ ---       ┆ ---  ┆   ┆ s_disablity    ┆ o_disablity   ┆ ---     ┆ ---         │
│ f64     ┆ f64    ┆ str       ┆ f64  ┆   ┆ ---            ┆ ---           ┆ f64     ┆ i32         │
│         ┆        ┆           ┆      ┆   ┆ i32            ┆ i32           ┆         ┆             │
╞═════════╪════════╪═══════════╪══════╪═══╪════════════════╪═══════════════╪═════════╪═════════════╡
│ 1.0     ┆ 2015.0 ┆ October   ┆ 25.0 ┆ … ┆ 0              ┆ 1             ┆ 40000.0 ┆ 1           │
│ 1.0     ┆ 2016.0 ┆ November  ┆ 1.0  ┆ … ┆ 0              ┆ 1             ┆ 47900.0 ┆ 1           │
│ 1.0     ┆ 2017.0 ┆ September ┆ 20.0 ┆ … ┆ 0              ┆ 1             ┆ 4000.0  ┆ 1           │
│ 1.0     ┆ 2018.0 ┆ October   ┆ 17.0 ┆ … ┆ 0              ┆ 1             ┆ 47000.0 ┆ 1           │
│ 1.0     ┆ 2019.0 ┆ October   ┆ 11.0 ┆ … ┆ 0              ┆ 1             ┆ 37000.0 ┆ 1           │
│ …       ┆ …      ┆ …         ┆ …    ┆ … ┆ …              ┆ …             ┆ …       ┆ …           │
│ 59400.0 ┆ 2022.0 ┆ January   ┆ 11.0 ┆ … ┆ 0              ┆ 1             ┆ 15000.0 ┆ 1           │
│ 59400.0 ┆ 2023.0 ┆ January   ┆ 21.0 ┆ … ┆ 0              ┆ 1             ┆ 19000.0 ┆ 1           │
│ 59400.0 ┆ 2024.0 ┆ November  ┆ 15.0 ┆ … ┆ 0              ┆ 1             ┆ 18000.0 ┆ 1           │
│ 59410.0 ┆ 2019.0 ┆ January   ┆ 28.0 ┆ … ┆ 0              ┆ 1             ┆ 29000.0 ┆ 1           │
│ 59410.0 ┆ 2021.0 ┆ November  ┆ 22.0 ┆ … ┆ 0              ┆ 1             ┆ 18000.0 ┆ 1           │
└─────────┴────────┴───────────┴──────┴───┴────────────────┴───────────────┴─────────┴─────────────┘

In [167]:
panel_common_2019_2020.filter(
    pl.col('is_employed_no_disablity') == 1
).group_by('year').len().plot.line(x='year', y='len')

alt.Chart(...)

In [168]:
panel_common_2019_2020.filter(
    pl.col('is_employed_has_disablity') == 1
).group_by('year').len().plot.line(x='year', y='len')

alt.Chart(...)

In [169]:
(
    panel_common_2019_2020
        #.filter((pl.col('is_employed_no_disablity') == 1)|(pl.col('is_employed_has_disablity') == 1))
        .filter(pl.col('h7_2').is_in(['October', 'November', 'December']))
        .filter(pl.col('working_pop') == 1)
        .with_columns(pl.col('year').cast(pl.Int32).cast(pl.String).str.to_date("%Y"))
        .group_by(['year', 'has_disablity']).agg(pl.col('net_job').mean())
).plot.line(x='year', y='net_job', color='has_disablity')

alt.Chart(...)

In [170]:
working_data = (
    panel_common_2019_2020

        .join(education_levels, on='educ', how='left', validate='m:1')
        .with_columns(pl.col('educ_level').fill_null('school_or_less'))
        .join(marital_status, on='marst', how='left', validate='m:1')
        .join(period_relevance, on='year', how='left', validate='m:1')
        .join(is_town, on='status', how='left', validate='m:1')
        .with_columns(pl.col('is_married').fill_null(0))
        .with_columns(
            is_female = pl.when(pl.col('h5') == 'FEMALE').then(1).otherwise(0),
        ).with_columns(
            pl.when(pl.col('chronic_heart') == 'Yes').then(1).otherwise(0).alias('chronic_heart'),
            pl.when(pl.col('chronic_lung') == 'Yes').then(1).otherwise(0).alias('chronic_lung'),
            pl.when(pl.col('chronic_liver') == 'Yes').then(1).otherwise(0).alias('chronic_liver'),
            pl.when(pl.col('chronic_kidney') == 'Yes').then(1).otherwise(0).alias('chronic_kidney'),
            pl.when(pl.col('chronic_stomach') == 'Yes').then(1).otherwise(0).alias('chronic_stomach'),
            pl.when(pl.col('chronic_spinal') == 'Yes').then(1).otherwise(0).alias('chronic_spinal'),
            pl.when(pl.col('disease_neuro') == 'Yes').then(1).otherwise(0).alias('disease_neuro'),
            pl.when(pl.col('disease_eye') == 'Yes').then(1).otherwise(0).alias('disease_eye'),
            pl.when(pl.col('allegies') == 'Yes').then(1).otherwise(0).alias('allegies')
        )
        #.filter(pl.col('idind').is_in(common_people))
).drop(cols_disease)
working_data = (
    working_data
        .rename({'status':'habitat'}).to_dummies('habitat')
        .to_dummies('educ_level')
        .to_dummies('disability_class')
        .drop('disability_class_no')
        .rename({'disability_class_First group':'disability_class_first_group', 'disability_class_Second group':'disability_class_second_group', 'disability_class_Third group':'disability_class_third_group'})
)
working_data

shape: (68_694, 47)
┌─────────┬────────┬───────────┬──────┬───┬────────────┬──────────────────┬─────────┬───────────┐
│ idind   ┆ year   ┆ h7_2      ┆ h7_1 ┆ … ┆ is_married ┆ period_relevance ┆ is_town ┆ is_female │
│ ---     ┆ ---    ┆ ---       ┆ ---  ┆   ┆ ---        ┆ ---              ┆ ---     ┆ ---       │
│ f64     ┆ f64    ┆ str       ┆ f64  ┆   ┆ i64        ┆ i64              ┆ i64     ┆ i32       │
╞═════════╪════════╪═══════════╪══════╪═══╪════════════╪══════════════════╪═════════╪═══════════╡
│ 1.0     ┆ 2015.0 ┆ October   ┆ 25.0 ┆ … ┆ 0          ┆ -4               ┆ 1       ┆ 1         │
│ 1.0     ┆ 2016.0 ┆ November  ┆ 1.0  ┆ … ┆ 0          ┆ -3               ┆ 1       ┆ 1         │
│ 1.0     ┆ 2017.0 ┆ September ┆ 20.0 ┆ … ┆ 0          ┆ -2               ┆ 1       ┆ 1         │
│ 1.0     ┆ 2018.0 ┆ October   ┆ 17.0 ┆ … ┆ 0          ┆ -1               ┆ 1       ┆ 1         │
│ 1.0     ┆ 2019.0 ┆ October   ┆ 11.0 ┆ … ┆ 0          ┆ 0                ┆ 1       ┆ 1         │
│ …       ┆ …      ┆ …         ┆ …    ┆ … ┆ …          ┆ …                ┆ …       ┆ …         │
│ 59400.0 ┆ 2022.0 ┆ January   ┆ 11.0 ┆ … ┆ 0          ┆ 3                ┆ 1       ┆ 1         │
│ 59400.0 ┆ 2023.0 ┆ January   ┆ 21.0 ┆ … ┆ 0          ┆ 4                ┆ 1       ┆ 1         │
│ 59400.0 ┆ 2024.0 ┆ November  ┆ 15.0 ┆ … ┆ 0          ┆ 5                ┆ 1       ┆ 1         │
│ 59410.0 ┆ 2019.0 ┆ January   ┆ 28.0 ┆ … ┆ 1          ┆ 0                ┆ 1       ┆ 1         │
│ 59410.0 ┆ 2021.0 ┆ November  ┆ 22.0 ┆ … ┆ 1          ┆ 2                ┆ 1       ┆ 1         │
└─────────┴────────┴───────────┴──────┴───┴────────────┴──────────────────┴─────────┴───────────┘

In [171]:
working_data = (
    working_data
        .filter(pl.col('h7_2').is_in(['October', 'November', 'December']))
    .group_by(['idind', 'year']).agg(
        pl.col('is_employed').mean(), pl.col('has_disablity').mean(), pl.col('j60').mean(), pl.col('net_job').mean(), pl.col('is_employed_has_disablity').last(), pl.col('age').last(), pl.col('is_female').last(), pl.col('is_town').last(), pl.col('educ_level_school_or_less').last(), pl.col('educ_level_common').last(), pl.col('educ_level_higher').last(), pl.col('educ_level_university').last(), pl.col('is_married').last(), pl.col('chronic_heart').last(), pl.col('chronic_lung').last(), pl.col('chronic_liver').last(), pl.col('chronic_kidney').last(), pl.col('chronic_stomach').last(), pl.col('chronic_spinal').last(), pl.col('disease_neuro').last(), pl.col('disease_eye').last(), pl.col('allegies').last(), pl.col('disability_class_first_group').last(), pl.col('disability_class_second_group').last(), pl.col('disability_class_third_group').last(), pl.col('period_relevance').last()
    )
    .sort(['idind', 'year'])
)
working_data

shape: (62_105, 28)
┌─────────┬────────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ idind   ┆ year   ┆ is_employe ┆ has_disabl ┆ … ┆ disability ┆ disability ┆ disabilit ┆ period_re │
│ ---     ┆ ---    ┆ d          ┆ ity        ┆   ┆ _class_fir ┆ _class_sec ┆ y_class_t ┆ levance   │
│ f64     ┆ f64    ┆ ---        ┆ ---        ┆   ┆ st_group   ┆ ond_group  ┆ hird_grou ┆ ---       │
│         ┆        ┆ f64        ┆ f64        ┆   ┆ ---        ┆ ---        ┆ p         ┆ i64       │
│         ┆        ┆            ┆            ┆   ┆ u8         ┆ u8         ┆ ---       ┆           │
│         ┆        ┆            ┆            ┆   ┆            ┆            ┆ u8        ┆           │
╞═════════╪════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 1.0     ┆ 2015.0 ┆ 1.0        ┆ 0.0        ┆ … ┆ 0          ┆ 0          ┆ 0         ┆ -4        │
│ 1.0     ┆ 2016.0 ┆ 1.0        ┆ 0.0        ┆ … ┆ 0          ┆ 0          ┆ 0         ┆ -3        │
│ 1.0     ┆ 2018.0 ┆ 1.0        ┆ 0.0        ┆ … ┆ 0          ┆ 0          ┆ 0         ┆ -1        │
│ 1.0     ┆ 2019.0 ┆ 1.0        ┆ 0.0        ┆ … ┆ 0          ┆ 0          ┆ 0         ┆ 0         │
│ 1.0     ┆ 2020.0 ┆ 1.0        ┆ 0.0        ┆ … ┆ 0          ┆ 0          ┆ 0         ┆ 1         │
│ …       ┆ …      ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 59398.0 ┆ 2021.0 ┆ 1.0        ┆ 0.0        ┆ … ┆ 0          ┆ 0          ┆ 0         ┆ 2         │
│ 59398.0 ┆ 2024.0 ┆ 1.0        ┆ 0.0        ┆ … ┆ 0          ┆ 0          ┆ 0         ┆ 5         │
│ 59400.0 ┆ 2021.0 ┆ 1.0        ┆ 0.0        ┆ … ┆ 0          ┆ 0          ┆ 0         ┆ 2         │
│ 59400.0 ┆ 2024.0 ┆ 1.0        ┆ 0.0        ┆ … ┆ 0          ┆ 0          ┆ 0         ┆ 5         │
│ 59410.0 ┆ 2021.0 ┆ 1.0        ┆ 0.0        ┆ … ┆ 0          ┆ 0          ┆ 0         ┆ 2         │
└─────────┴────────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [172]:
# working_data = working_data.filter(
#     pl.col('idind').is_in(
#         working_data.filter(pl.col('year').is_in([2019, 2020]))['idind'].unique().implode()
#     )
# )
# working_data

In [173]:
working_data.filter(pl.col('is_employed_has_disablity') == 1).plot.boxplot(y='net_job').properties(width=100, height=350)

alt.Chart(...)

In [174]:
working_data.filter(pl.col('is_employed_has_disablity') == 0).plot.boxplot(y='net_job').properties(width=100, height=350)

alt.Chart(...)

In [175]:
ids_to_exclude_0 = working_data.filter(pl.col('is_employed_has_disablity') == 0).filter(pl.col('net_job') > 500_000)['idind'].to_list()
#ids_to_exclude_0 = []
ids_to_exclude_0

[4326.0,
 14137.0,
 14137.0,
 14137.0,
 14137.0,
 14137.0,
 26759.0,
 35638.0,
 36089.0,
 36635.0,
 39478.0,
 49130.0,
 50863.0,
 51399.0,
 51399.0,
 51497.0,
 52451.0]

In [176]:
ids_to_exclude_1 = working_data.filter(pl.col('is_employed_has_disablity') == 1).filter(pl.col('net_job') > 120000)['idind'].to_list()
ids_to_exclude_1 = [x for x in ids_to_exclude_1 if x not in [7399, 40749]]
ids_to_exclude_1

[33674.0, 58780.0, 58791.0, 59156.0, 59156.0]

In [182]:
(
    working_data
        .filter(~pl.col('idind').is_in(ids_to_exclude_0 + ids_to_exclude_1))
        .with_columns(pl.col('year').cast(pl.Int32).cast(pl.String).str.to_date("%Y"))
        .group_by(['year', 'is_employed_has_disablity']).agg(pl.col('net_job').mean())
).plot.line(x='year', y='net_job', color='is_employed_has_disablity')

alt.Chart(...)

In [178]:
panel2019_2020 = (
    working_data
        # .filter(pl.col())
        .filter(~pl.col('idind').is_in(ids_to_exclude_0 + ids_to_exclude_1))
        .filter(pl.col('year').is_in([2019, 2020]))
        .with_columns(pl.col('year').cast(pl.Int32).cast(pl.String).str.to_date("%Y"))
        .filter(pl.col('idind').is_duplicated())
).to_pandas().set_index(['idind', 'year'])
panel2019_2020

                    is_employed  has_disablity       j60   net_job  \
idind   year
1.0     2019-01-01          1.0            0.0   37000.0   37000.0
        2020-01-01          1.0            0.0   37000.0   37000.0
3.0     2019-01-01          1.0            1.0   38100.0   20600.0
        2020-01-01          0.0            1.0   19700.0     700.0
6.0     2019-01-01          1.0            0.0   30500.0   30500.0
...                         ...            ...       ...       ...
59268.0 2020-01-01          1.0            0.0   26300.0   26300.0
59271.0 2019-01-01          1.0            0.0   40000.0   40000.0
        2020-01-01          1.0            0.0   36000.0   36000.0
59274.0 2019-01-01          0.0            0.0   18980.0       0.0
        2020-01-01          1.0            0.0  118996.0  100000.0

                    is_employed_has_disablity   age  is_female  is_town  \
idind   year
1.0     2019-01-01                          0  46.0          1        1
        2020-01-01                          0  47.0          1        1
3.0     2019-01-01                          1  64.5          1        1
        2020-01-01                          0  65.5          1        1
6.0     2019-01-01                          0  33.5          0        1
...                                       ...   ...        ...      ...
59268.0 2020-01-01                          0  27.5          1        1
59271.0 2019-01-01                          0  34.5          0        1
        2020-01-01                          0  35.5          0        1
59274.0 2019-01-01                          0  59.5          1        1
        2020-01-01                          0  61.0          1        1

                    educ_level_school_or_less  educ_level_common  ...  \
idind   year                                                      ...
1.0     2019-01-01                          0                  0  ...
        2020-01-01                          0                  0  ...
3.0     2019-01-01                          0                  0  ...
        2020-01-01                          0                  0  ...
6.0     2019-01-01                          0                  1  ...
...                                       ...                ...  ...
59268.0 2020-01-01                          0                  0  ...
59271.0 2019-01-01                          0                  0  ...
        2020-01-01                          0                  0  ...
59274.0 2019-01-01                          0                  0  ...
        2020-01-01                          0                  0  ...

                    chronic_kidney  chronic_stomach  chronic_spinal  \
idind   year
1.0     2019-01-01               0                0               0
        2020-01-01               0                0               0
3.0     2019-01-01               0                1               0
        2020-01-01               0                1               0
6.0     2019-01-01               0                0               0
...                            ...              ...             ...
59268.0 2020-01-01               0                0               0
59271.0 2019-01-01               0                0               0
        2020-01-01               0                0               0
59274.0 2019-01-01               0                0               0
        2020-01-01               0                0               0

                    disease_neuro  disease_eye  allegies  \
idind   year
1.0     2019-01-01              0            0         0
        2020-01-01              0            0         0
3.0     2019-01-01              0            0         0
        2020-01-01              0            0         0
6.0     2019-01-01              0            0         0
...                           ...          ...       ...
59268.0 2020-01-01              0            0         0
59271.0 2019-01-01              0            0         0
        2020-01-01              0            0         0
59274.0 2019-01-01              0            0         0
        2020-01-01              0            0         1

                    disability_class_first_group  \
idind   year
1.0     2019-01-01                             0
        2020-01-01                             0
3.0     2019-01-01                             0
        2020-01-01                             0
6.0     2019-01-01                             0
...                                          ...
59268.0 2020-01-01                             0
59271.0 2019-01-01                             0
        2020-01-01                             0
59274.0 2019-01-01                             0
        2020-01-01                             0

                    disability_class_second_group  \
idind   year
1.0     2019-01-01                              0
        2020-01-01                              0
3.0     2019-01-01                              0
        2020-01-01                              0
6.0     2019-01-01                              0
...                                           ...
59268.0 2020-01-01                              0
59271.0 2019-01-01                              0
        2020-01-01                              0
59274.0 2019-01-01                              0
        2020-01-01                              0

                    disability_class_third_group  period_relevance
idind   year
1.0     2019-01-01                             0                 0
        2020-01-01                             0                 1
3.0     2019-01-01                             1                 0
        2020-01-01                             1                 1
6.0     2019-01-01                             0                 0
...                                          ...               ...
59268.0 2020-01-01                             0                 1
59271.0 2019-01-01                             0                 0
        2020-01-01                             0                 1
59274.0 2019-01-01                             0                 0
        2020-01-01                             0                 1

[11934 rows x 26 columns]

In [183]:
(
    working_data
        # .filter(pl.col())
        .filter(~pl.col('idind').is_in(ids_to_exclude_0 + ids_to_exclude_1))
        .filter(pl.col('year').is_in([2019, 2020]))
        .with_columns(pl.col('year').cast(pl.Int32).cast(pl.String).str.to_date("%Y"))
        .filter(pl.col('idind').is_duplicated())
)

shape: (11_934, 28)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ idind   ┆ year       ┆ is_employ ┆ has_disab ┆ … ┆ disabilit ┆ disabilit ┆ disabilit ┆ period_re │
│ ---     ┆ ---        ┆ ed        ┆ lity      ┆   ┆ y_class_f ┆ y_class_s ┆ y_class_t ┆ levance   │
│ f64     ┆ date       ┆ ---       ┆ ---       ┆   ┆ irst_grou ┆ econd_gro ┆ hird_grou ┆ ---       │
│         ┆            ┆ f64       ┆ f64       ┆   ┆ p         ┆ up        ┆ p         ┆ i64       │
│         ┆            ┆           ┆           ┆   ┆ ---       ┆ ---       ┆ ---       ┆           │
│         ┆            ┆           ┆           ┆   ┆ u8        ┆ u8        ┆ u8        ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1.0     ┆ 2019-01-01 ┆ 1.0       ┆ 0.0       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│ 1.0     ┆ 2020-01-01 ┆ 1.0       ┆ 0.0       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 1         │
│ 3.0     ┆ 2019-01-01 ┆ 1.0       ┆ 1.0       ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 0         │
│ 3.0     ┆ 2020-01-01 ┆ 0.0       ┆ 1.0       ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 1         │
│ 6.0     ┆ 2019-01-01 ┆ 1.0       ┆ 0.0       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│ …       ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 59268.0 ┆ 2020-01-01 ┆ 1.0       ┆ 0.0       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 1         │
│ 59271.0 ┆ 2019-01-01 ┆ 1.0       ┆ 0.0       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│ 59271.0 ┆ 2020-01-01 ┆ 1.0       ┆ 0.0       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 1         │
│ 59274.0 ┆ 2019-01-01 ┆ 0.0       ┆ 0.0       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│ 59274.0 ┆ 2020-01-01 ┆ 1.0       ┆ 0.0       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 1         │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [185]:
model1 = PanelOLS.from_formula('np.log(net_job + 1) ~ has_disablity + EntityEffects', data=panel2019_2020).fit(cov_type='clustered', cluster_entity=True, group_debias=False)
print(model1.summary)

                           PanelOLS Estimation Summary
=================================================================================
Dep. Variable:     np.log(net_job + 1)   R-squared:                        0.0020
Estimator:                    PanelOLS   R-squared (Between):             -0.0097
No. Observations:                11934   R-squared (Within):               0.0020
Date:                 Tue, Apr 21 2026   R-squared (Overall):             -0.0094
Time:                         12:52:22   Log-likelihood                -2.236e+04
Cov. Estimator:              Clustered
                                         F-statistic:                      12.159
Entities:                         5967   P-value                           0.0005
Avg Obs:                        2.0000   Distribution:                  F(1,5966)
Min Obs:                        2.0000
Max Obs:                        2.0000   F-statistic (robust):             4.9155
                                         P-value                           0.0267
Time periods:                        2   Distribution:                  F(1,5966)
Avg Obs:                        5967.0
Min Obs:                        5967.0
Max Obs:                        5967.0

                               Parameter Estimates
=================================================================================
               Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
---------------------------------------------------------------------------------
has_disablity    -2.2424     1.0114    -2.2171     0.0267     -4.2251     -0.2596
=================================================================================

F-test for Poolability: 1.8848
P-value: 0.0000
Distribution: F(5966,5966)

Included effects: Entity

In [186]:
model2 = PanelOLS.from_formula('net_job ~ has_disablity + EntityEffects + TimeEffects', data=panel2019_2020).fit(cov_type='clustered', cluster_entity=True, group_debias=False)
print(model2.summary)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:                net_job   R-squared:                        0.0005
Estimator:                   PanelOLS   R-squared (Between):             -0.0063
No. Observations:               11934   R-squared (Within):               0.0005
Date:                Tue, Apr 21 2026   R-squared (Overall):             -0.0058
Time:                        13:04:05   Log-likelihood                -1.276e+05
Cov. Estimator:             Clustered
                                        F-statistic:                      2.9892
Entities:                        5967   P-value                           0.0839
Avg Obs:                       2.0000   Distribution:                  F(1,5965)
Min Obs:                       2.0000
Max Obs:                       2.0000   F-statistic (robust):             2.8044
                                        P-value                           0.0941
Time periods:                       2   Distribution:                  F(1,5965)
Avg Obs:                       5967.0
Min Obs:                       5967.0
Max Obs:                       5967.0

                               Parameter Estimates
=================================================================================
               Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
---------------------------------------------------------------------------------
has_disablity    -7501.6     4479.6    -1.6746     0.0941  -1.628e+04      1280.0
=================================================================================

F-test for Poolability: 4.0654
P-value: 0.0000
Distribution: F(5967,5965)

Included effects: Entity, Time